"""
Tests for Trainer: time-series CV no-leakage and P50 blend formula.

Feature: mhtcet-cutoff-prediction
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

from app.trainer import Trainer, FEATURE_COLUMNS, TARGET_COLUMN, _blend_p50


# ---------------------------------------------------------------------------
# Helpers — synthetic feature-engineered DataFrame
# ---------------------------------------------------------------------------

def _make_fe_df(
    years: list[int],
    n_per_year: int = 20,
    seed: int = 42,
) -> pd.DataFrame:
    """Build a minimal feature-engineered DataFrame for testing.

    All FEATURE_COLUMNS are filled with random floats; TARGET_COLUMN and
    auxiliary columns (year, category, cap_round, branch_name) are also
    included so the Trainer can run end-to-end.
    """
    rng = np.random.default_rng(seed)
    rows = []
    categories = ["OPEN", "OBC", "SC"]
    cap_rounds = ["I", "II", "III"]
    branches = [f"branch_{i}" for i in range(5)]

    for year in years:
        for i in range(n_per_year):
            row: dict = {
                "year": year,
                "category": categories[i % len(categories)],
                "cap_round": cap_rounds[i % len(cap_rounds)],
                "branch_name": branches[i % len(branches)],
                TARGET_COLUMN: float(rng.uniform(50, 95)),
            }
            for col in FEATURE_COLUMNS:
                row[col] = float(rng.uniform(0, 100))
            rows.append(row)

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Property 14: Time-series CV no-leakage
# Feature: mhtcet-cutoff-prediction, Property 14: Time-series CV no-leakage
# Validates: Requirements 3.1
# ---------------------------------------------------------------------------

@given(
    years=st.lists(
        st.integers(min_value=2015, max_value=2030),
        min_size=2,
        max_size=6,
        unique=True,
    ).map(sorted),
    n_per_year=st.integers(min_value=10, max_value=30),
)
@settings(max_examples=50, deadline=None)
def test_property_14_cv_no_leakage(years: list[int], n_per_year: int) -> None:
    """Property 14: Time-series CV no-leakage.

    For any CV fold generated by the trainer, every training sample must
    have `year` strictly less than the validation year.
    """
    df = _make_fe_df(years, n_per_year=n_per_year)
    trainer = Trainer()
    folds = trainer.build_folds(df)

    # There must be at least one valid fold when we have ≥2 years with
    # enough rows per year.
    for df_train, df_val in folds:
        val_years = df_val["year"].unique()
        assert len(val_years) == 1, "Validation fold should contain exactly one year"
        val_year = val_years[0]

        # Core no-leakage assertion
        assert (df_train["year"] < val_year).all(), (
            f"Training fold contains rows with year >= val_year={val_year}. "
            f"Train years: {sorted(df_train['year'].unique())}"
        )


# ---------------------------------------------------------------------------
# Property 15: P50 blend formula
# Feature: mhtcet-cutoff-prediction, Property 15: P50 blend formula
# Validates: Requirements 3.4
# ---------------------------------------------------------------------------

@given(
    lgbm_vals=st.lists(
        st.floats(min_value=0.0, max_value=100.0, allow_nan=False, allow_infinity=False),
        min_size=1,
        max_size=200,
    ),
    ridge_vals=st.lists(
        st.floats(min_value=0.0, max_value=100.0, allow_nan=False, allow_infinity=False),
        min_size=1,
        max_size=200,
    ),
)
@settings(max_examples=50, deadline=None)
def test_property_15_p50_blend_formula(
    lgbm_vals: list[float], ridge_vals: list[float]
) -> None:
    """Property 15: P50 blend formula.

    For any pair of lgbm_p50 and ridge_p50 arrays, the blended output must
    equal 0.70 * lgbm_p50 + 0.30 * ridge_p50 within floating-point tolerance.
    """
    # Align lengths
    n = min(len(lgbm_vals), len(ridge_vals))
    assume(n >= 1)

    lgbm_arr = np.array(lgbm_vals[:n])
    ridge_arr = np.array(ridge_vals[:n])

    blended = _blend_p50(lgbm_arr, ridge_arr)
    expected = 0.70 * lgbm_arr + 0.30 * ridge_arr

    np.testing.assert_allclose(
        blended,
        expected,
        atol=1e-9,
        err_msg="Blended P50 does not match 0.70*lgbm + 0.30*ridge",
    )


# ---------------------------------------------------------------------------
# Unit tests — basic sanity checks
# ---------------------------------------------------------------------------

def test_trainer_dry_run_returns_metrics() -> None:
    """Trainer.train with dry_run=True returns a metrics dict without writing files."""
    import tempfile, os
    df = _make_fe_df([2021, 2022, 2023], n_per_year=20)
    trainer = Trainer()
    with tempfile.TemporaryDirectory() as tmp:
        result = trainer.train(df, tmp, dry_run=True)

    assert "validation_mae" in result
    assert "validation_within_1_accuracy" in result
    assert "validation_directional_accuracy" in result
    assert "calibration_coverage" in result
    assert "metrics_by_category" in result
    assert "metrics_by_cap_round" in result
    assert "metrics_by_branch" in result


def test_trainer_requires_at_least_two_years() -> None:
    """Trainer.train raises ValueError when only one year is present."""
    df = _make_fe_df([2022], n_per_year=20)
    trainer = Trainer()
    with pytest.raises(ValueError, match="at least 2 distinct years"):
        trainer.train(df, "/tmp/unused", dry_run=True)


def test_trainer_missing_feature_column_raises() -> None:
    """Trainer.train raises ValueError when a required feature column is missing."""
    df = _make_fe_df([2021, 2022], n_per_year=20)
    df = df.drop(columns=["cutoff_t1"])
    trainer = Trainer()
    with pytest.raises(ValueError, match="missing required columns"):
        trainer.train(df, "/tmp/unused", dry_run=True)


def test_build_folds_no_leakage_simple() -> None:
    """build_folds: training rows always have year < validation year."""
    df = _make_fe_df([2020, 2021, 2022], n_per_year=15)
    trainer = Trainer()
    folds = trainer.build_folds(df)
    assert len(folds) >= 1
    for df_train, df_val in folds:
        val_year = df_val["year"].unique()[0]
        assert (df_train["year"] < val_year).all()


def test_blend_p50_scalar() -> None:
    """_blend_p50 scalar check: 0.70*80 + 0.30*60 == 74.0."""
    result = _blend_p50(np.array([80.0]), np.array([60.0]))
    assert abs(result[0] - 74.0) < 1e-9
